import Head from "next/head";
import { useState } from "react";
import MyButton from "./my-button";

export default function Home() {
  const [count,setCount]=useState(0);
  const increaseCounter=()=>{
    setCount(count+1);
  }
  const decreaseCounter=()=>{
    setCount(count-1);
  }
  const handleInput=(e)=>{
    const value=e.target.value;
    setCount(Number(value));
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
     <h1 className="heading">Hello {count}</h1>
     <button onClick={increaseCounter}>inc count</button>
     <button onClick={decreaseCounter}>dec count</button>
     <MyButton text="increase" onClick={increaseCounter}/>
     <input
     onInput={handleInput}
     />

      </main>
    </>
  );
}
